### ISSUE TITLE
What does the "for multi supervised mode" mean?

### ISSUE THREAD

**Issue by pzz2011** [opteroncx/SESR#2]
Hi, there,
   I find the branchLoss in the following:
> https://github.com/opteroncx/SESR/blob/master/main.py#L132

  can you explain the multi supervised mode detaily? I am confused about it.
  thanks!

**Comment by opteroncx** [comment]
supervise each recursion in each branch, simply enable this by moving
        output = self.upsample(x)
        list_out.append(output)
and
HR_2x.append(tmp)
HR_4x.append(tmp)
into the for statement. This could gain higher PSNR (0.01~0.03dB), but lead to more computation.

**Comment by pzz2011** [comment]
so, you mean that the implementation now has not adopted "the supervised mode" ?

**Comment by pzz2011** [comment]
another question, how long should this recursion model train on the Yang91+BSD200?

**Comment by opteroncx** [comment]
10~15 min per epoch( batchsize=64) , with NVIDIA Tesla P40
and totally I runned 300 epochs

**Comment by pzz2011** [comment]
thanks
